# name: WIF
# env:
#   project_id: db-cicdpipeline-wave-2
# on:
#   workflow_dispatch:
# permissions:
#   contents: read
#   pages: write
#   id-token: write
# jobs:
#   wif:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout code
#         uses: actions/checkout@v3
#       - name: Auth Google cloud
#         uses: google-github-actions/auth@v1
#         with:
#           token_format: 'access_token'
#           workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
#           service_account: ${{ secrets.SA }}
#       - name: List Compute instances
#         run: |
#           gcloud compute instances list --project ${{ env.project_id }}
